tosend 2022-06-12 18:47:11+00:00

diff --git a/tests/lib b/tests/lib
--- a/tests/lib
+++ b/tests/lib
@@ -2,8 +2,13 @@
 
 . ./env
 
-## I would use the builtin !, but that has the wrong semantics.
-not () { "$@" && exit 1 || :; }
+# I would use the builtin !, but that has the wrong semantics
+not () {
+  if "$@" || test $? = "4"; then
+    # fail the test if command succeeds or returns 4
+    exit 1
+  fi
+}
 
 # trick: OS-detection (if needed)
 os_is_windows() {
@@ -27,10 +32,10 @@ if os_is_windows; then
   git config --global core.autocrlf input
 fi
 
-pwd() {
-    ghc --make -o hspwd "$TESTBIN/hspwd.hs" > /dev/null
-    "./hspwd"
-}
+# tests now work on windows with this or with the bash pwd:
+# pwd() {
+#     runghc "$TESTBIN/hspwd.hs"
+# }
 
 which() {
     type -P "$@"
