tosend 2023-06-26 19:16:57+00:00

diff --git a/tests/lib b/tests/lib
--- a/tests/lib
+++ b/tests/lib
@@ -2,8 +2,15 @@
 
 . ./env
 
-## I would use the builtin !, but that has the wrong semantics.
-not () { "$@" && exit 1 || :; }
+# I would use the builtin !, but that has the wrong semantics
+not () {
+  set +x
+  if "$@" || test $? = "4"; then
+    # fail the test if command succeeds or returns 4
+    exit 1
+  fi
+  set -x
+}
 
 # trick: OS-detection (if needed)
 os_is_windows() {
@@ -27,10 +34,10 @@ if os_is_windows; then
   git config --global core.autocrlf input
 fi
 
-pwd() {
-    ghc --make -o hspwd "$TESTBIN/hspwd.hs" > /dev/null
-    "./hspwd"
-}
+# tests now work on windows with this or with the bash pwd:
+# pwd() {
+#     runghc "$TESTBIN/hspwd.hs"
+# }
 
 which() {
     type -P "$@"
@@ -120,5 +127,11 @@ compare_bundles() {
 grep -q darcs-3 .darcs/defaults && format=darcs-3
 grep -q darcs-2 .darcs/defaults && format=darcs-2
 grep -q darcs-1 .darcs/defaults && format=darcs-1
+
+# To test if darcs works correctly in case hard-linking fails because the
+# cache is in a different file system. This assumes that /run/darcs-test is
+# writable and on a separate filesystem (e.g. tmpfs).
+#
+# export XDG_CACHE_HOME=`mktemp -d -p /run/darcs-test`
 
 set -vex -o pipefail
